# Site settings
title: Lærerkonferanse 2015 Tromsø
# email: bjorn@cs.uit.no, einar@cs.uit.no
description: > # this means to ignore newlines until "baseurl:"
  Lærerkonferanse i programmering. Arrangeres 14. september 2015. 
baseurl: "/laererkonferanse" # the subpath of your site, e.g. /blog/
url: "http://fjukstad.github.io/laererkonferanse" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
